name: Go Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: ソースをチェックアウト
        uses: actions/checkout@v3

      - name: Go をセットアップ
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: golangci-lint をセットアップ
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Lint 実行
        run: golangci-lint run ./...
